### ISSUE TITLE
Build a user dashboard / settings page

### ISSUE THREAD

**Issue by dessalines** [dessalines/lemmy#141]
So far, the only settings I can think of are:

- Show NSFW
- Possibly tags / flair?

**Comment by mister-monster** [comment]
Will this settings page control the UI or their account? I think those two sets of settings ought to be separated because the web UI you've built will probably not be the only UI used. Native apps for different operating systems will also be used that will probably have their own UI settings.

Also with regard to flair, do you have any intention of having per community flair? 

I'd say as far as global UI settings some good options would be default sort, show thumbnails, possibly even show chat pane since a lot of users have discussed the pros and cons of the chat pane, if it isn't too difficult.

**Comment by dessalines** [comment]
Their account. Currently I don't have any database table or rows for account settings. Any app could change a users settings through the API. 

Flair should be a separate issue, im not sure how it should, if its self creating self tagging, if its global, or local to a community, if its

**Comment by dessalines** [comment]
Fixed by the #198 , which adds a settings page.
