### ISSUE TITLE
feature request: templated comments

### ISSUE THREAD

**Issue by ghost** [dessalines/lemmy#162]
On github a repo owner can write a certain template for people that are opening new issues. This doesn't force a user to use it tho, the user can delete it all and write something completly different - this is the idea behind "templated comments" for lemmy. This feature will allow community admins (and OPs) to add such a templated comment, if they choose to and regular users to use it or delete it and write something else.

note: it should not apply to comment replies, only to comments to the main topic.

**Comment by dessalines** [comment]
Is this kinda like the *Be Civil* / code of conduct you see on reddit comments / posts? 

Also would this would be community-wide right? IE the community mods set this up in the community settings, like the sidebar?

**Comment by Zig-03** [comment]
> Is this kinda like the _Be Civil_ / code of conduct you see on reddit comments / posts?

I don't understand the reference you're using but perhaps this explanaition will make things look a bit clearer: 
If you're logged into reddit, using the new reddit design, open any post and in the box where you type your comment you'll see a text _"What are your thoughts?"_ - this is a placeholder but it looks similar to the idea of this suggestion, with the exception that the text should be editable by community mods and it should be real text that users can interract with (delete, edit,etc).

> Also would this would be community-wide right?

It could be like that or community mods could allow OPs (people who post things) to set a custom template for their posts. For example, in a community called Fishing someone creates a post called "Please critique my fishing equipment" and sets a template like:

[I like these things] :
[I dislike these things] :

Now when someone will want to leave a comment in that post, there will already be that "placeholder" and if that user decies to use it, he'll write soemthing like:

[I like these things] : your fishing rod, this, that, and that
[I dislike these things] : your bag, etc, etc, etc.

Someone else tho could delete that template and write something else:

I think ..... But this looks ... And because...



_btw what we call a subreddit on reddit is called a community on lemmy? Or you don't have a name for it yet?_

**Comment by dessalines** [comment]
I'll have to hear from others on how they feel about this, this is one of those things that should be voted on.

Making it the text, then just letting users edit it might not be a good idea, ppl would hate having to edit every comment to delete the text they don't want. 

I'd be up for the idea of html placeholders possibly, but this might even be considered an extra unecessary bloat by some.

Ya its called a community.

**Comment by nickkelley42** [comment]
As long as it's not a resource hog, it could be a useful feature. It seems like it could be a decent way to encourage a certain set of norms for a conversation/community.

It might make sense to allow community moderators to set a default template, and then allow individual users to tweak the template on their own posts.

Eg, on a community for sharing users' art, the admins could set a default template, something like above:

    I like...
    I dislike...

But then if a user was asking a more specific set of questions, they could tweak it to, say:

    [how can I make the sky color better?]
    [how do I make the tree seem more natural?]

It could be a simple textarea for the OP, just below the main post body textarea; the default value would be whatever the community mods set (or empty if none), and the poster could delete it if they don't want to include it.

I think as people used it communities would start to establish norms around the use of templates; if users of the artwork community always have to delete the template because they hate it, the mods/posters would just do away with them. But for some communities this could be very useful.

I could also see good arguments against using this. Maybe it could be an optional feature for admins to turn on/off on a per-server/per-community basis?
