### ISSUE TITLE
attempt to create a deleted community gives error saying it already exists

### ISSUE THREAD

**Issue by anewton1998** [dessalines/lemmy#168]
I deleted the main community. Then used the create community button to create a new community with the same name of "main". I then get an error saying the community already exists.

**Comment by dessalines** [comment]
This is something that needs to be figured out yet and discussed. Every front end delete in lemmy isn't a real DB delete, but really just setting a database column, and removing it from searches, and sometimes just putting a *deleted* tombstone there.

DB deleting a community would delete all its posts and comments, never to be restored. Currently you can restore deleted and removed communities.

IMO the best way to do it would be to have the ability to transfer ownership of communities, rather than creating an already existing but deleted community, then the new owners / mods could remove whatever they see fit. Imma call this a dup of #139
