### ISSUE TITLE
feature request: featured communities

### ISSUE THREAD

**Issue by anewton1998** [dessalines/lemmy#169]
As a feature, perhaps the instance admin could pick communities to be "featured" and listed above the other communities on the communities page.

**Comment by dessalines** [comment]
We were having a discussion about defaults in the matrix chat, and settled for now at least on having a default community called `main`, that new users are subbed to by default. But even after you sign up, it redirects you to the communites page, to sub to more.

I did want to avoid the reddit thing of subbing you to a bunch of defaults which inevitably turn to shit. But I don't mind the idea of having featured communities listed above the others, at least on the communities page. 

This might not even really be too necessary, since you could also link the featured communities on your site sidebar. Its on the backburner at least for me rn.

**Comment by anewton1998** [comment]
100% agree that this is not a priority.

**Comment by mister-monster** [comment]
I think one thing that should be avoided is a "frontpage" of "default" communities. let people get involved in what they want to get involved in of their own volition

**Comment by anewton1998** [comment]
My thought here is that, much like Mastodon, many instances focus on a topic or community. With federation and activitypub, a community that wants to be about knitting and related topics might get its focus overrun by political communities because fediverse wide they might always have a high number of posts. Therefore, a featured communities would allow an instance to be a little more focused.
