### ISSUE TITLE
The "Chat" component is confusing

### ISSUE THREAD

**Issue by trosel** [dessalines/lemmy#237]
Is it a module that is separate from the comments below an article? If so, I would make the UI look more distinct. Maybe draw a box around it.

Or are the "chats" the comments themselves, ordered by most recent and updated in real time? If so, I would not use the term "Chat". Maybe go with something like "Most recent". But even in this case, "conversations" usually occur via nested replies. Conversations are difficult to follow if they're all just posting on the same level. So I'm not sure how helpful a separate "Chat" area even is for facilitating conversation.

If it's a live-feed of most recent comments, I suggest removing the separate Chat (https://github.com/dessalines/lemmy/issues/235) component and making the live updating feature of comments more obvious in the normal comments area. 

You already have a "New" ordering option for comments. Maybe add a Live Feed option next to that?

**Comment by Nutomic** [comment]
> Or are the "chats" the comments themselves, ordered by most recent and updated in real time?

Its this. Agree with your other points, having it side by side is not that great.

**Comment by dessalines** [comment]
@Nutomic is right, the chat section is the exact same data as the comment tree, just flat (instead of nested / in a tree) like chat, and sorted by recent instead of the custom sort for the tree.

This is one I want to fight for, and I'll explain why. Also I wanna say that I'm very open to UI changes around how it looks and such, but I still want to keep two panes (1 for the tree, 1 for the flat).

So when you have comments in a tree, even if you sort the tree by new, you don't actually see new info at the top. The new comment might be many branches down in the tree. Then you have to stick that entire comment chain above all the others. To illustrate why a tree sorted by new isn't that useful:

```
top comment 1
 - branch
    - branch
      ... 10 more branches down
        ... comment posted one minute ago

top comment 2
 - branch
    - branch
      ... 10 more branches down
        ... comment posted two minutes ago
```

This is why chat apps, although they _could_ show the data in a tree, never do, because you can't get that freely updating feel where ppl are responding in real time, because they'd have to scroll all around the page to find the new comments. 

The reason it seems useless right now, is that the communities aren't big enough yet to have many active participants replying at the same time. When one gets to that point, even if its just 3 people active in the same minute, you'll see why the chat sidebar is useful. 

Having both panes, one tree, sorted for hot comments, by score, and one flat, sorted by new, lets ppl have the best of both worlds. The chat sidebar also is by default scrolled to the top, no matter where you are in the page: ![example](https://i.imgur.com/IKJiTJW.png)

So you can easily see new comments, and respond to them, even if you are responding somewhere further down in the tree. I'm excited to see how this will work for live events, stickied chatrooms, and so forth. I think the tipping point will be threads that consistently get 30+ comments, which are very common on reddit but not yet on lemmy, it still growing.

I might add a user setting to turn off the chat bar #235 , but I think this is one where ppl are dismissing it before seeing its usefulness.

**Comment by dessalines** [comment]
I am trying out some different things here.

Making the chat text smaller, and making it a card:

![](https://i.imgur.com/Yi3b4uK.png)

**Comment by dessalines** [comment]
Moving the chat all the way over. This is a little less than ideal because subs might have some very long sidebars, and it would take a long time to see the chat.

![](https://i.imgur.com/QbSfJCz.png)

**Comment by dessalines** [comment]
Also maybe rename `Chat` to `Recent`?

**Comment by Nutomic** [comment]
Recent sounds more accurate, and you can also put a description in a tooltip.

**Comment by PopeRigby** [comment]
> I might add a user setting to turn off the chat bar #235 , but I think this is one where ppl are dismissing it before seeing its usefulness.

Even so, I would still add a setting. This is definitely sonething people will want to turn off.

**Comment by trosel** [comment]
@dessalines 

>the chat section is the exact same data as the comment tree, just flat (instead of nested / in a tree) like chat, and sorted by recent instead of the custom sort for the tree.

In this case, the functionality seems to be in the same realm as "hot / top / new".

What about adding it as an additional option there? To me, that makes it clear that it is dealing with the same data. 

"hot / top / new / live feed"

> So you can easily see new comments, and respond to them, even if you are responding somewhere further down in the tree. 

How does this work in practice? If you want the Chat to be used in that manner, you should reduce the friction for people to "instant reply".

Problem is that any reply is going to be lacking context and could be seen as a useless addition to the conversation because of it. 

--- 

Also, for what it's worth, "chat" is confusing especially now because Reddit recently added an actual chat / real-time messaging functionality for sub-reddits and such.

**Comment by dessalines** [comment]
This is on the sidebar now and not that obtrusive.
