### ISSUE TITLE
It is possible to upload images without logging in

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#297]
To reproduce:

1. visit a lemmy instance
2. log out from any account
3. click on "create post"
4. click "upload image"

It would also make sense to hide the buttons for create post/create community if the current user is not logged in.

![Screenshot_20191016_115933](https://user-images.githubusercontent.com/1044450/66909171-d1f78480-effb-11e9-991c-97aa806909d0.png)

**Comment by dessalines** [comment]
Yup this is a bug. 

I'm still debating either completely hiding things that not-logged-in users can't do (IE don't even show create post / community buttons /textareas), or just having the popup dialog like I have now. With the second one, its kinda nice because you can see all the functionality of the site, even if you haven't made an account yet.
