### ISSUE TITLE
ESLint + Prettier

### ISSUE THREAD

**Issue by zacanger** [dessalines/lemmy#305]
Would you mind if I added some basic linting and possibly Prettier to the UI setup, as git/npm hooks? It would help keep things consistent and help prevent issues from future contributors (myself included).

**Comment by dessalines** [comment]
This already has a linting thing for typescript, the `tslint.json` file, but when I ran it using --fix, it broke the project, so I've held off on doing that for now. At some point I will get around to doing all the fixes it recommends, and figuring out why its breaking the project.

you can test it using : 

`tslint --project .` 

But for now at least, and with the PR you have too, I'd prefer no linting / simple formatting changes. I don't like them because there's a tendency for ppl to "own lines" when they really only ran a linter on something someone else wrote. 

I'll leave this open for when I do eventually go through and fix everything.

**Comment by zacanger** [comment]
Ah, alright, I missed that for some reason. I try to avoid tslint because it's a Palantir project, and is also deprecated.

I have a branch [here](https://github.com/dessalines/lemmy/compare/master...zacanger:chore/lint#diff-df7b4d33b423182326ea26470c69f630R1) using ESLint with the TypeScript plugin, if you're interested in looking into switching, but I won't put that in as a PR since it also brings in Prettier.

**Comment by dessalines** [comment]
This does look pretty cool, once I get a chance to look at it more, I'll think about adding this.

**Comment by dessalines** [comment]
Okay I tested it out, and it works and I really like it. Would you like to do a PR with just the lint files, and the new package.json so u get the cred for this?
