### ISSUE TITLE
docker/dev: Keep build cache

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#336]
It seems like the dev docker build does not keep any build cache, which makes incremental compilation and development rather slow. 

Unfortunately, it seems like there is no real solution for this problem (or I didnt find it in my quick search). But here are some discussions:

https://vsupalov.com/cache-docker-build-dependencies-without-volume-mounting/
https://stackoverflow.com/q/26050899
https://github.com/moby/moby/issues/14080

**Comment by dessalines** [comment]
It should, I spent a long time making sure it does. It never says `Using cache` when you rebuild it on your machine? It should cache every step.

**Comment by Nutomic** [comment]
Sorry I should have been clearer. The dependencies are cached just fine. However, the actual compilation (`cargo build --frozen`) is not cached at all, and takes a couple of minutes for me after every little change.

**Comment by dessalines** [comment]
Ah yeah, that would. It usually takes less than 10 seconds for me. 

Would it be helpful if I made another dev dockerfile that doesn't use --release, like your PR?

**Comment by Nutomic** [comment]
Probably not, the compilation didnt seem any faster that way. Maybe I need to try developing on my other computer.

**Comment by Nutomic** [comment]
Okay you must have a really fast computer. Even on my fast laptop (quadcore intel i7), it takes 2 minutes to build after a single whitespace change.

**Comment by dessalines** [comment]
Faaack that's not good. I have same laptop, core i7. The only thing I can think of, is maybe the docker version / install.

**Comment by Nutomic** [comment]
I have these versions on both devices (from Manjaro repos)

```
Docker version 19.03.4-ce, build 9013bf583a
docker-compose version 1.24.1, build unknown
```

**Comment by Nutomic** [comment]
With dependencies its the same problem. Because it doesnt use any cache, installing or updating a single crate means you have to install everything from scratch, and that takes a few minutes. Maybe I should just install everything outside of Docker...

**Comment by dessalines** [comment]
Yeah those versions should be fine.

Ohhh okay. Yeah so when you update or make any changes to the `Cargo.toml`, it does have to rebuild the entire cache and that does take a long ass time. Its unavoidable with docker unfortunately, since there's no good `--build-dependencies` option except for the workaround this uses.

Overall tho this shouldn't be too annoying, since there shouldn't be too many changes to the `Cargo.toml`. But for any code updates, it shouldn't take more than a minute (takes my meh system ~ 30 seconds, and using a code editor that works with rust also helps).

Also btw may I ask what editor you're using? I use `coc.nvim` with vim and the `coc-rls`, so it checks all the errors on the codebase while I'm coding, and only takes a few seconds to do the check after I've stopped typing. I'm told vscode and intellij also have good rust support.

**Comment by Nutomic** [comment]
Yeah I'm using intellij, but the checks arent always correct I think. So my plan now is to compile locally, and just use the docker-compose once the compile is working without errors.

**Comment by iav** [comment]
@Nutomic , on a second compilation `cargo build --frozen` - you see a compilation of all dependecies and lemmy, or only lemmy?

**Comment by Nutomic** [comment]
@iav When I run `docker-compose up --no-deps --build` and any dependency has changed, it rebuilds all dependencies. If no dependencies have changed, but the Lemmy code has, it only rebuilds all of Lemmy.

**Comment by dessalines** [comment]
Closing this, there's nothing I can do about it unfortunately, its just the only way the community has found for docker to cache cargo deps. And still if any one of them changes, it requires a full rebuild.

**Comment by Nutomic** [comment]
Maybe we could use [sccace](https://github.com/mozilla/sccache/) for this, but it would probably be complicated to setup.
