### ISSUE TITLE
Too many requests. 1 per 3600 seconds

### ISSUE THREAD

**Issue by chopin2712** [dessalines/lemmy#353]
I wanted to create a community but a pop-up message appears with this message:
`Too many requests. 1 per 3600 seconds`

I never created other community before, and even though, this is hard! 1 HOUR?

I think it is an error, can you help me?

PS: This Reddit clone is amazing!

**Comment by dessalines** [comment]
Thx! The default rate limits are [here](https://github.com/dessalines/lemmy/blob/master/docs/api.md#rate-limits), but any self-hosted instance can change them.

The 1 hour is only for new accounts and community creation, because of some early spammers. I might lower it at some point, but don't want them wide open for obvious reasons.

**Comment by chopin2712** [comment]
Thanks! Yes I understand. But how can I change it? Can I do it using the docker-compose file?

**Comment by Nutomic** [comment]
@chopin2712 You can edit the .env file to change the rate limits. Posts and everything else are stored in the database.
