### ISSUE TITLE
Very weird translations

### ISSUE THREAD

**Issue by chopin2712** [dessalines/lemmy#356]
Hello, I am a French-speaking person and I created a small instance of Lemmy. 
I wanted to test if other computers on the network could access to my server. 
I tested it on a French computer, and I was very surprised by the translations, I first thought it was a weird Google Translation but because I tested it on Firefox, this is not Google Translate.

Also, there is no button to switch language. 

For instance: 

“Communauté en Vogue” sounds weird in French, this is a very old way of saying “Trending Communities” 

“Chaud” is NEVER used to say Hot (Trending). The correct translation would be “Tendance”, literally “Trending”. 

There is also other things like this, so I don't know how the translation stuff works but this is not correct translations. It would be better to set the basic language to English.

**Comment by Nutomic** [comment]
You can update the translations by editing [this file](https://github.com/dessalines/lemmy/blob/master/ui/src/translations/fr.ts) and making a PR with your changes.

But I think it would be a good idea to setup a proper tool for translation management, because most translators wont be familiar with git (and it would have some extra features just for translating). Maybe [Weblate](https://weblate.org/en/), or something else?

**Comment by chopin2712** [comment]
@Nutomic I've created a pull request to fix the translations. I don't know what is Weblate can you explain more? Is not seems to be something FOR translations.

**Comment by Nutomic** [comment]
@chopin2712 Its a self-hosted website that can be used to manage software translations. Because doing translations through git is not very efficient. However I dont have any experience with it.

**Comment by dessalines** [comment]
Fixed by #357
