### ISSUE TITLE
Move "appoint as mod/admin" buttons 

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#386]
This layout makes it really easy to turn someone into a mod or admin by accident (there isnt even a confirmation).

![Screenshot_20191229_230628](https://user-images.githubusercontent.com/1044450/71563445-8b0c1d80-2a87-11ea-8607-be335e7dd801.png)

It would probably make sense to put these options into the community/website configuration.

**Comment by dessalines** [comment]
I *could* build `Are you sure` dialogs here (I've done that for deleting communities I think), but as soon as you click any of those 4 ban/appoint buttons, the `unban` shows up, and you can instantly revert them. IE the ban button changes to unban. So they're super easy to click, but also easy to undo, and in that sense aren't destructive.

Also, it was a conscious choice to add the mod actions done on comments (and posts now too), rather than other spots, mainly coming from experience modding reddit subs. For example on reddit, without RES, you have to go to a special community mod page, and copy-paste their username into a text box, to ban them, or appoint them as mods.

There are other UI things we could do (maybe add them all after link, and a spacer?), but I do want to keep that consistent bolded text as actions.

**Comment by Nutomic** [comment]
Maybe move them behind some kind of three dot menu? Right now it seems really easy to press one of those options by accident, maybe without even noticing, and then the easy revert also doesn't help. The confirmation dialogue should definitely be there, because the consequences might be pretty serious.

**Comment by dessalines** [comment]
I added are you sure dialogs to these, and added some separators.
