### ISSUE TITLE
Feature Request: Define your languages on your profile

### ISSUE THREAD

**Issue by hhassey** [dessalines/lemmy#391]
After defining the languages that you want to see in your profile, filter everything to only those languages.  This will be very useful when federation connects the whole world in Lemmy.

Congratulations @dessalines keep up the good work! and happy 2020.

**Comment by dessalines** [comment]
This isn't possible, since communities and posts don't have tagged languages. In reality tho, a community will mostly be in one language, so anyone would just subscribe to the communities of languages they speak. If you don't speak spanish and don't want to learn, you probably won't subscribed to a spanish speaking sub.

The language setting is just for the UI.
