### ISSUE TITLE
Improve experience for users that are not logged in

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#450]
If you are not logged in, a lot of actions are show even though you cant use them:

- Upvote/downvote buttons are simply disabled. This seems fine, but maybe show some non-annoying indicator that the user needs to login for voting.
- Options for creating posts, comments and communities are all available, but submitting something shows a dialog "you havent logged in". It would be better to hide these actions in that case.

**Comment by dessalines** [comment]
Before I had a browser alert for comments, I can add that back in. Another possibility, is any action that requires you to be logged in, to navigate you to the login page. I've seen other sites do that.

**Comment by Nutomic** [comment]
Yeah in a way that you go back to the previous page after logging in. Though it still makes sense to hide some things like the community creation until the user logs in.

**Comment by dessalines** [comment]
I changed the post and comment upvoting to show the toast error now, but I still want to show the create post and community button pages for non-logged in users, since it shows the possiblity of what you can do logged in. If you try to do those things, it will show the same toast errors as all the others when being logged in is required.
