### ISSUE TITLE
Implement a "filter" model of moderating communities.

### ISSUE THREAD

**Issue by StaticallyTypedRice** [dessalines/lemmy#497]
Original comment on Reddit: https://old.reddit.com/r/rust/comments/eq16bp/lemmy_v060_release_an_open_source_reddit/fg8x0g5/?context=3

One huge complaint of Reddit is that once a community name is created, it essentially belongs to the person who created it, and they alone can appoint other moderators and basically shape the community into what they want. However, a problem arises if the original moderator group is less than friendly and turns the community into something toxic. I can see this happening with "buzzword" communities like /c/politics on some instances, where a person grabs it and turns it into an echo chamber where only their views are allowed. 

## Here's a potential solution

I remember seeing an old suggestion on /r/RedditAlternatives that could be really interesting: Have an unlimited number of "filters" on a community, each of which is a discrete group of moderators. All the filters moderate the same content of a community and do as they please, but anyone can make a filter and invite other mods.

Another option is to allow everyone the ability to moderate everything and simply have users choose which mods' decisions to apply and in what priority. This will allow for the most customization and is probably easier to implement.

In both of these cases, removed content will still be visible if a user switches to an "unfiltered" view.

It'll be up to the admins and site-wide mods to remove content that breaks site-wide rules.

I've seen this idea brought up here and there, and it sounds really interesting. What do all of you think? Is this something Lemmy could think about implementing sometime in the (probably not very near) future?

**Comment by dessalines** [comment]
I'm not a fan of these filtering / choose your own mod solutions. Its way too complicated for the user (now they have to actively pick their own filters / mods, rather than just subscribing to a community), not to mention the fact that the community moderators / creators now don't really have moderation ability over their communities. A community is like a curated forum, or a newspaper, and part the investment in it 

One thing is that the biggest subs, (might be news or politics on a general-purpose lemmy), will likely be controlled or at least curated by the admins as well, and they can appoint mods, or transfer the communities from inactive mods.

There probably will emerge some good ideas about how to do more democratic moderation, bc what you're saying is definitely a problem, but lets keep that in #417 .
