### ISSUE TITLE
Disable signups by default

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#499]
I think its a good idea to disable signups by default, because if I setup an instance for testing, I dont want random people or bots to sign up and start posting. Once the instance is fully configured, signups can manually be opened by the admin.

We could also add a config value for this that differs between debug and prod deployments, but I'm not sure how that could work as the signups_enabled variable is currently stored in the database.

**Comment by dessalines** [comment]
Closing in favor of #404.

**Comment by dessalines** [comment]
Whoops, wrong one.

**Comment by dessalines** [comment]
Okay so if they give an initial site setup in the `lemmy.hjson`, they can explicitly disable signups on creation. 

But I don't want this to be a default value, because I know the first question that will be asked hundreds of times is "okay I setup my site, but my users say they're getting a message saying registration is closed".
