### ISSUE TITLE
Better community name

### ISSUE THREAD

**Issue by lucasdondo** [dessalines/lemmy#533]
What I will say now can make Lemmy a more attractive, user-friendly and beautiful platform, which will make users more productive and interested while using this service.
Why don't implement upper-case support and stops in the communitie's names? Minimum that, and better if it can support also slashes and more signs.

**Comment by StaticallyTypedRice** [comment]
I agree on the capital letters suggestion. CamelCase is the way to go for multi-word community names.

**Comment by dessalines** [comment]
Communities have required names, AND titles. Titles are what you actually see when you go to the community page, and they can have upper cases and even spaces. The names are really just for unique urls.

**Comment by lucasdondo** [comment]
> Communities have required names, AND titles. Titles are what you actually see when you go to the community page, and they can have upper cases and even spaces. The names are really just for unique urls.

Unique URLs can't have capital letters? This will improve your project seamlessly. Your users will really appreciate that (Besides me and @StaticallyTypedRice, haha). If you want you can delegate this simple and cool feature (I'd love to do so, but I don't know much about programming). Maybe you can even post in /c/announcements for help in this.

**Comment by dessalines** [comment]
No, this is a really bad idea.

**Comment by StaticallyTypedRice** [comment]
> No, this is a really bad idea.

It can be hard to discern different words in community names otherwise, because two phrases could have the same combined spelling. A fun example is "superbowl" which can mean "SuperBowl" or "SuperbOwl". Reddit capitalized on this joke and made the /r/superbowl subreddit about owls. This will only get worse when you get into longer names. 

A really easy way of dealing with this is to allow mixed-case formatting but single case identities. Reddit and Github uses this. When you type in FooBar, the server converts it to foobar before sending it to the database, and you're not allowed to have a FoObar be something else. It will however redirect your URL to FooBar even if you typed in foobar. It's about human readability, both in URLs and in community name mentions.

**Comment by Nutomic** [comment]
@dessalines Could you explain why this is a bad idea?

**Comment by dessalines** [comment]
- You can already have underscores in community names, so the superb_owl point is moot.
- URLs add no value, and browsers should remember page titles. This is why the post URLs just have numbers, but if you type the post name in your browser url bar, the correct post should come up. 
- As I said abov,  communities already have a title field, which can have spaces and anything you want. It makes sense to have strict community identifiers, but longer titles. 
- I just got asked to implement lowercase uniqueness for usernames, why would I remove that for communities. 
- Luis is asking me to put slashes in community names, they really don't know about URL limitations.
