### ISSUE TITLE
Move image thumbnailing, and iframely code to the back-end.

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#558]
If you open the network tab of your browser dev tools, you can see that opening the main page of dev.lemmy.ml causes a total of 52 requests until the site is fully loaded. Thats a lot, and I dont believe we need all of those. There are a lot of requests for `geturl` and `oembed`. While I'm not sure what exactly these do, this looks like work that should be done just once in the backend, without putting any additional logic on the frontend. And it should probably be part of the API, cause any apps would want to access thumbnails and embeds as well.

---

Out of these, I think I narrowed it down to only needing to add these optional columns to the post table:

- iframely_title
- iframely_html
- iframely_description
- pictshare_url

TODOs

- [x] Add columns to post table
- [ ] Do pictshare and iframely fetches on the back-end
- [ ] Create one-off job to update these columns for existing posts
- [x] Update front end to use new columns for post fetches.

And I think I wanna move all this work to the back end, so any potential future clients don't need to embed any of this.

The only negative that comes with this, is that iframes html embeds might be sometimes off, but that can always be corrected by re-running the one-off job.

**Comment by dessalines** [comment]
There are two JSON requests its doing right now:

- Fetching the oembed. (Iframely smartly caches these results)
- Calling pictshare with that oembed thumbnail (and pictshare smartly caches, so its not actually posting the image twice, really just checking if its there, and returning the hash / url)

The first one is averaging under 1 KB, the second one is about 1B per post with a url. So the size is minimal, and nothing compared to even the cached image fetches.

The alternative is storing the iframely data on a post creation, (things like thumbnail_url, description, html_code), in the DB, which I don't like doing because oembeds are dynamic data that can change at any point.

The other reason I don't wanna store extra info attached to the post table, is because eventually I want even clients to potentially be able to embed / expand images and whatever other content.

**Comment by dessalines** [comment]
I'm not fully decided on this btw, because I think it probably would be a lot more efficient to move all iframely work to the back end, and add a bunch of nullable columns to the post table. 

Here's some of the iframely data. I'm currently only using url, title, thumbnail_url, description, and html.

```
export interface FramelyData {
  url: string;
  type: string;
  version?: string;
  title: string;
  author?: string;
  author_url?: string;
  provider_name?: string;
  thumbnail_url?: string;
  thumbnail_width?: number;
  thumbnail_height?: number;
  description?: string;
  html?: string;
}
```

**Comment by dessalines** [comment]
Out of these, I think I narrowed it down to only needing to add these optional columns to the post table:

- iframely_title
- iframely_html
- iframely_description
- pictshare_url

And I think I wanna move all this work to the back end, so any potential future clients don't need to embed any of this.

**Comment by Nutomic** [comment]
@dessalines you can just put the todos in my original post, easier to find there
