### ISSUE TITLE
Better distinction between external links and embedded images

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#564]
Or can you tell at a glance which of these items open an embed and which open a new link? We should make this clearer, eg by making the hover overlay for external links persistent. Discussion threads should also have a generic icon in the same size to keep the layout consistent.

![Screenshot_20200229_024023](https://user-images.githubusercontent.com/1044450/75598572-8a4a3480-5a94-11ea-9941-b14ed2238379.png)

**Comment by Nutomic** [comment]
So what I'm saying is, **every** post should have a thumbnail at the left:

- image post: just the image thumbnail, same as now
- link post: image thumbnail, but with the overlay icon always visible
- discussion post: a generic "discussion" icon, clicking it opens the post

The icons should also all have a consistent size with proper cropping, because the current layout is just a mess and completely unaligned. Readability would be a lot better if we could just put all the identical things in identical columns.

**Comment by StaticallyTypedRice** [comment]
I think this is a good idea. There should also be an icon on every thumbnail showing what clicking on it does so people don't have to mouseover to the thumbnail to find out, and also to accommodate mobile users which don't have mouseover support.

**Comment by dessalines** [comment]
I like this idea, I'll mess around with fixed-width image and image placeholders to get this working.

Question tho: what would be the best way to differentiate image posts, and link posts (that have a thumbnail)? Right now I'm doing a mouseover (which I want to get rid of since as @StaticallyTypedRice its pointless on mobile), but would a little icon indicator on the top right of each image be a good way?

**Comment by Nutomic** [comment]
@dessalines My suggestion for that is to use the current indicator that is shown on mouseover, but make it always visible.

**Comment by Nutomic** [comment]
Now links have the tiny icon again, I was thinking to use the icon in the same size as before in the mouseover, because like this its really hard to see.

**Comment by StaticallyTypedRice** [comment]
> Now links have the tiny icon again, I was thinking to use the icon in the same size as before in the mouseover, because like this its really hard to see.
> 
> Edit: Also the icons for links without a thumbnail are kind of ugly, they need something like a frame.

I think they should be square and a lighter grey with the icon centered on it.

**Comment by dessalines** [comment]
I'm not going to do the mouseover stuff, because they're useless on mobile anyway. The icons on the top right are just for showing content type now, they don't do anything more. 

I also don't want that content-type icon to cover the whole image, I want you to be able to see the whole thumbnail.

I tried framing the icons, it looked really bad. 

I don't wanna do any grey, because that might not look good on different themes.

@StaticallyTypedRice If you can mock some of these up in code tho, I'd be willing to take a look.

**Comment by Nutomic** [comment]
Well right now the icons are too small to really see them, at least make them bigger.
