### ISSUE TITLE
Load custom CSS from folder

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#596]
Basically we could create a folder next to the config where admins can put their own CSS code in order to customize their instance. That means they don't have to bother with compiling their themed Lemmy version.

**Comment by dessalines** [comment]
I don't wanna make it easy for admins to do this. I'd rather bootstrap themes be added in the standard way so all instances could take advantage of them. 

And I also am currently against admin-based theming, and would prefer **users** to be the ones to choose their preferred theme, and all visual customization be at the user level.

**Comment by Nutomic** [comment]
> I don't wanna make it easy for admins to do this. I'd rather bootstrap themes be added in the standard way so all instances could take advantage of them.

But then it still needs to be tested, and it doesnt make sense to force people to compile the whole project just to try some different css. So whether its a debug option or a production option to load custom css, its something that we need to support. 

And people will probably want to create a lot of themese that dont need to go into our source code, that would just mean more maintenance burden for us. Really I dont see any reason why we cant provide this as an option in production, we can still let users override the defaults.

**Comment by dessalines** [comment]
If they're a css expert, the most likely way they'd be testing out things anyway, is through a browser plugin that lets them load / edit css styles on any website they're on. You can even use the debug tools on FF or chrome to do this.

I could create a css guide, but either way, the front end can only load things in the assets folder, which requires a build. I *could* change this so that it copies some resources out, but I def don't want to deal with the security implications of that. Letting instances inject their own css or js outside of the open-source codebase sounds pretty dangerous.

**Comment by Nutomic** [comment]
Okay the guide should definitely help, and then we can see if we get more requests for this kind of feature.
