### ISSUE TITLE
Disable the slurs filter

### ISSUE THREAD

**Issue by hawkoon** [dessalines/lemmy#621]
How do I completely disable the slurs filter, for both site setup and posts?

**Comment by dessalines** [comment]
Not disabling the slur filter, ever. Use voat or gab if you want to say racist slurs.

**Comment by hawkoon** [comment]
Merely asking for an option for people who use your software to disable the filter. The software developer shouldn't be the one who gets to decide what you can or can't say, that's up to the website owner.

**Comment by hawkoon** [comment]
> 
> 
> Not disabling the slur filter, ever. Use voat or gab if you want to say racist slurs.

Kind of weird you immediately screeched "I'm not disabling it!" when I was **clearly** asking how I, as a site owner, could do it for my own instance.

**Comment by dessalines** [comment]
> Merely asking for an option for people who use your software to disable the filter. 

We're not giving users or site owners the "option" or "freedom" to use racist and sexist slurs, that goes against our code of conduct, and the goals of this project. Go to voat or gab if you want to be racist, its pretty simple.

> screeched

That's a ban.

**Comment by grravity** [comment]
I can understand this on the official instance(s), but this would not be a problem for users who decide to self-host an instance in the future and want to have it completely open and uncensored correct?

**Comment by dessalines** [comment]
There will never be an "uncensored" version of Lemmy, it will always have a slur filter to remove sexist, racist, and transphobic content. You can go to voat or gab for an "uncensored" reddit experience.

**Comment by grravity** [comment]
So essentially, you have a voice over all instances, to approve what you deem to be a slur or racist, or sexist. Defeating the entire purpose of Federation, Decentralization. If you end up seeing stuff you don't like, you could essentially just add that stuff to the censor-list/code of conduct, and all instances would have to follow. 
Imo this goes entirely against the ideals of the Fediverse as a whole. Yes there's instances that don't allow stuff, but that doesn't mean someone else can't erect a new instance that wants to allow uncensored discussion. Again, I can understand not wanting it on official instances, but to apply it as a generalized thing and say NOBODY can create an instance that it doesn't apply to, that's very confusing and frustrating. 
We are looking for platforms where we as users are in control, not one or one group of people. Otherwise we'd just continue to use centralized options which do the same thing.

Not trying to stir shit, or be a dick, but I think it's important to speak out. Imho this is a retarded move and really should be reconsidered.

**Comment by dessalines** [comment]
> Defeating the entire purpose of Federation, Decentralization.

The point of federation is to have the "freedom" to say racist shit?

Banned for using an ableist slur.

**Comment by leventea** [comment]
Just make the remove_slurs function return the original value. It's not too hard to uncuck lemmy.

**Comment by Granitosaurus** [comment]
> > Defeating the entire purpose of Federation, Decentralization.
> 
> The point of federation is to have the "freedom" to say racist shit?
> 
> Banned for using an ableist slur.

here's is a direct quote of the banned slurs:
```
static ref SLUR_REGEX: Regex = RegexBuilder::new(r"(fag(g|got|tard)?|maricos?|cock\s?sucker(s|ing)?|\bn(i|1)g(\b|g?(a|er)?(s|z)?)\b|dindu(s?)|mudslime?s?|kikes?|mongoloids?|towel\s*heads?|\bspi(c|k)s?\b|\bchinks?|niglets?|beaners?|\bnips?\b|\bcoons?\b|jungle\s*bunn(y|ies?)|jigg?aboo?s?|\bpakis?\b|rag\s*heads?|gooks?|cunts?|bitch(es|ing|y)?|puss(y|ies?)|twats?|feminazis?|whor(es?|ing)|\bslut(s|t?y)?|\btr(a|@)nn?(y|ies?)|ladyboy(s?)|\b(b|re|r)tard(ed)?s?)").case_insensitive(true).build().unwrap();
```

Yes, the racist slurs like ladyboy, cock, slut and twat!
FYI ladyboy is not a slur or even offensive term; source: I'm from Thailand where the term originated.

You hardcore your own prude ignorance into the project which is rather disappointing. Also this filter is laughable easy to avoid with a random space by bad actors and does nothing but create a bunch of false positives and censor legitimate linguistic or meta  discussion.

Very disappointed with this response :-1:

**Comment by dessalines** [comment]
> source: I'm from Thailand where the term originated.

![image](https://user-images.githubusercontent.com/930215/89912538-acf28480-dbc0-11ea-8552-75f78f54627e.png)
